"""
Test.assert_equals(color_pattern_times(["Red", "Green", "Blue", "Yellow", "Red", "Red", "Yellow", "Green", "Green", "Green", "Red", "Blue", "Yellow", "Blue", "Green", "Green", "Red", "Red", "Red", "Blue", "Green", "Red", "Blue", "Blue", "Red", "Blue"]), 70)
Test.assert_equals(color_pattern_times(["Red", "Blue", "Yellow", "Blue", "Green", "Green", "Yellow", "Green", "Blue", "Blue", "Blue", "Red", "Blue", "Red", "Green", "Red"]), 44)
Test.assert_equals(color_pattern_times(["Yellow", "Green", "Blue"]), 8)
Test.assert_equals(color_pattern_times(["Green", "Green", "Red", "Green", "Yellow", "Red", "Red", "Green", "Red", "Green"]), 27)
Test.assert_equals(color_pattern_times(["Red"]), 2)
Test.assert_equals(color_pattern_times(["Red", "Red", "Blue", "Red", "Green", "Red", "Blue", "Green", "Green", "Yellow", "Red"]), 30)
Test.assert_equals(color_pattern_times(["Green", "Green", "Blue", "Red", "Red", "Blue", "Yellow", "Red", "Red", "Green", "Yellow", "Red", "Yellow", "Red", "Green", "Yellow", "Red", "Green", "Yellow", "Blue", "Yellow", "Red", "Green", "Green", "Blue", "Yellow", "Green", "Green", "Green", "Blue"]), 83)
Test.assert_equals(color_pattern_times(["Red", "Blue", "Red", "Blue", "Green", "Blue", "Yellow", "Blue", "Yellow", "Yellow", "Yellow", "Red"]), 33)
Test.assert_equals(color_pattern_times(["Yellow", "Green", "Yellow", "Yellow"]), 10)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Yellow", "Green", "Green", "Red", "Blue", "Yellow", "Red", "Yellow", "Green", "Red", "Yellow", "Green", "Yellow", "Blue", "Yellow", "Green", "Green", "Blue"]), 56)
Test.assert_equals(color_pattern_times(["Red", "Blue", "Yellow", "Blue", "Green", "Yellow", "Yellow", "Yellow", "Yellow", "Red", "Red", "Yellow", "Yellow"]), 33)
Test.assert_equals(color_pattern_times(["Blue", "Red", "Red"]), 7)
Test.assert_equals(color_pattern_times(["Red", "Blue", "Yellow", "Green", "Blue", "Yellow", "Blue", "Yellow", "Red", "Green", "Green", "Blue", "Blue", "Green", "Green", "Red", "Green", "Red", "Green", "Red", "Red", "Green", "Red", "Red", "Green", "Red", "Blue", "Yellow", "Red", "Red"]), 83)
Test.assert_equals(color_pattern_times(["Yellow", "Blue", "Yellow", "Yellow", "Yellow", "Blue", "Blue"]), 17)
Test.assert_equals(color_pattern_times(["Yellow", "Red", "Green", "Green", "Yellow", "Green", "Green", "Yellow", "Yellow", "Red", "Green", "Green", "Blue", "Green", "Red", "Yellow"]), 43)
Test.assert_equals(color_pattern_times(["Red", "Red", "Blue", "Yellow", "Red", "Red", "Red", "Yellow", "Blue", "Blue", "Yellow", "Yellow", "Red", "Yellow", "Red", "Blue", "Blue", "Yellow", "Yellow", "Blue", "Blue", "Yellow", "Red", "Blue", "Red", "Blue", "Red", "Yellow", "Blue"]), 78)
Test.assert_equals(color_pattern_times(["Yellow", "Red", "Green"]), 8)
Test.assert_equals(color_pattern_times(["Green", "Red", "Yellow", "Yellow", "Blue", "Red", "Blue", "Blue", "Yellow", "Red", "Yellow", "Green", "Green", "Red", "Green", "Blue", "Green", "Red", "Blue", "Yellow", "Red"]), 59)
Test.assert_equals(color_pattern_times(["Yellow", "Red", "Blue", "Green", "Red", "Green", "Yellow", "Yellow", "Yellow", "Red", "Green", "Blue", "Blue"]), 35)
Test.assert_equals(color_pattern_times(["Green", "Blue", "Blue", "Red", "Yellow", "Red", "Red", "Yellow", "Red", "Red", "Blue", "Red", "Red"]), 34)
Test.assert_equals(color_pattern_times(["Yellow", "Yellow", "Red", "Blue"]), 10)
Test.assert_equals(color_pattern_times(["Green", "Red", "Red", "Blue", "Yellow", "Blue", "Yellow", "Yellow", "Green", "Red", "Red", "Green", "Red", "Yellow", "Yellow", "Green", "Green", "Yellow", "Blue", "Blue", "Red", "Yellow", "Red", "Blue", "Red", "Blue", "Blue", "Yellow", "Blue", "Yellow"]), 82)
Test.assert_equals(color_pattern_times(["Red", "Blue", "Green", "Yellow", "Yellow", "Yellow", "Yellow", "Blue"]), 20)
Test.assert_equals(color_pattern_times(["Green", "Red", "Green", "Red", "Yellow", "Green", "Green", "Red", "Red", "Yellow", "Green", "Yellow", "Yellow", "Yellow"]), 37)
Test.assert_equals(color_pattern_times(["Yellow", "Red", "Green", "Blue", "Blue", "Red", "Red", "Yellow", "Red", "Green", "Red"]), 30)
Test.assert_equals(color_pattern_times(["Yellow", "Yellow", "Blue", "Yellow", "Green", "Yellow", "Green", "Green", "Red", "Yellow", "Blue", "Green", "Green", "Green"]), 37)
Test.assert_equals(color_pattern_times(["Green", "Green", "Red", "Green", "Blue", "Blue", "Red", "Yellow", "Red", "Yellow", "Green"]), 30)
Test.assert_equals(color_pattern_times(["Yellow", "Green", "Yellow", "Green", "Yellow", "Green", "Blue", "Green", "Blue", "Green", "Red", "Red", "Blue", "Yellow", "Green", "Blue"]), 46)
Test.assert_equals(color_pattern_times(["Red", "Green", "Green", "Blue", "Red", "Green", "Green", "Red", "Yellow", "Blue", "Red", "Red", "Yellow", "Blue", "Blue"]), 40)
Test.assert_equals(color_pattern_times(["Yellow", "Yellow", "Red", "Yellow", "Blue", "Blue", "Blue", "Red", "Blue", "Red", "Yellow", "Red", "Red", "Red", "Yellow", "Blue", "Green", "Blue", "Blue", "Yellow", "Green"]), 56)
Test.assert_equals(color_pattern_times(["Green", "Green", "Red", "Green", "Blue"]), 13)
Test.assert_equals(color_pattern_times(["Red", "Yellow", "Red", "Green", "Blue", "Red", "Red", "Red", "Green", "Blue"]), 27)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Blue", "Blue", "Blue", "Green", "Yellow", "Red", "Yellow", "Red", "Red", "Green", "Blue", "Yellow", "Green", "Yellow", "Green"]), 45)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Blue", "Blue", "Green", "Green", "Yellow", "Blue", "Blue", "Red", "Yellow", "Green", "Yellow", "Red", "Blue", "Red", "Yellow"]), 45)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Blue", "Red", "Yellow", "Red", "Blue", "Blue", "Blue", "Yellow"]), 25)
Test.assert_equals(color_pattern_times(["Green", "Red", "Green", "Blue", "Blue", "Blue"]), 15)
Test.assert_equals(color_pattern_times(["Red", "Yellow", "Red", "Yellow", "Green", "Blue", "Yellow", "Yellow"]), 22)
Test.assert_equals(color_pattern_times(["Blue", "Red", "Red", "Blue", "Yellow", "Red", "Yellow", "Yellow", "Blue", "Yellow", "Blue", "Red", "Blue", "Green", "Yellow", "Red", "Red", "Red", "Green", "Yellow", "Red", "Blue", "Green"]), 64)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Blue", "Yellow"]), 9)
Test.assert_equals(color_pattern_times(["Red", "Red", "Blue"]), 7)
Test.assert_equals(color_pattern_times(["Green", "Blue", "Blue", "Blue", "Yellow", "Yellow", "Red", "Yellow", "Blue", "Red", "Yellow", "Blue"]), 32)
Test.assert_equals(color_pattern_times(["Green", "Red", "Green", "Yellow", "Green", "Yellow", "Green"]), 20)
Test.assert_equals(color_pattern_times(["Green", "Red", "Blue", "Green", "Green", "Yellow", "Red", "Green", "Blue", "Green", "Yellow", "Yellow", "Red", "Green", "Yellow", "Green", "Green", "Blue", "Yellow", "Green", "Green", "Blue", "Yellow", "Red", "Red", "Red", "Green", "Green"]), 76)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Red", "Yellow", "Green", "Yellow", "Green", "Red", "Blue", "Blue", "Red", "Green", "Blue", "Yellow", "Yellow", "Green", "Blue", "Red", "Yellow", "Red", "Green", "Yellow", "Green", "Green", "Green", "Yellow", "Red"]), 75)
Test.assert_equals(color_pattern_times(["Blue", "Red", "Red", "Yellow", "Red", "Yellow", "Yellow", "Yellow", "Yellow", "Red", "Yellow", "Red", "Blue", "Red", "Blue", "Red", "Red", "Yellow", "Green", "Red", "Red", "Blue", "Red", "Yellow", "Yellow", "Blue", "Green", "Green", "Yellow", "Red"]), 81)
Test.assert_equals(color_pattern_times(["Yellow", "Yellow", "Yellow", "Red", "Green", "Red"]), 15)
Test.assert_equals(color_pattern_times(["Blue", "Red", "Yellow"]), 8)
Test.assert_equals(color_pattern_times(["Blue", "Red", "Red", "Green", "Red", "Yellow", "Red", "Red", "Green", "Yellow", "Blue", "Yellow", "Yellow", "Red", "Yellow", "Red", "Blue", "Yellow"]), 50)
Test.assert_equals(color_pattern_times(["Yellow", "Green", "Red", "Green", "Green", "Blue", "Blue", "Blue", "Yellow", "Green", "Yellow", "Yellow", "Yellow", "Red", "Green", "Green", "Blue", "Green", "Yellow", "Red", "Green", "Blue", "Green", "Red", "Green", "Red"]), 71)
Test.assert_equals(color_pattern_times(["Green", "Blue", "Yellow", "Yellow", "Red", "Red", "Red", "Red", "Red", "Green", "Blue", "Blue", "Red", "Yellow", "Red", "Red", "Red", "Red", "Blue", "Yellow", "Yellow"]), 52)
Test.assert_equals(color_pattern_times(["Yellow", "Red", "Blue", "Red", "Green", "Yellow", "Red", "Blue", "Blue", "Green", "Green", "Blue", "Blue", "Green", "Blue", "Red", "Yellow"]), 47)
Test.assert_equals(color_pattern_times(["Yellow", "Yellow", "Blue", "Yellow", "Green", "Green", "Yellow", "Green", "Green", "Green", "Green", "Yellow", "Blue", "Blue", "Blue", "Green", "Green", "Green", "Yellow", "Blue", "Red"]), 53)
Test.assert_equals(color_pattern_times(["Green", "Yellow", "Yellow"]), 7)
Test.assert_equals(color_pattern_times(["Blue", "Yellow", "Yellow", "Green", "Blue", "Yellow", "Green", "Green", "Green", "Yellow", "Red", "Yellow", "Green", "Red", "Red", "Blue", "Yellow", "Blue", "Blue", "Red"]), 54)
Test.assert_equals(color_pattern_times(["Green"]), 2)
Test.assert_equals(color_pattern_times(["Green", "Blue"]), 5)
Test.assert_equals(color_pattern_times(["Green", "Blue", "Red", "Blue", "Yellow", "Yellow", "Green", "Green", "Yellow", "Blue", "Green", "Red", "Green", "Yellow", "Green", "Blue", "Red", "Red", "Red", "Red", "Red"]), 56)
Test.assert_equals(color_pattern_times(["Blue", "Yellow", "Blue", "Red", "Green", "Blue", "Yellow", "Red", "Blue", "Red", "Yellow", "Green", "Green", "Yellow", "Green", "Red", "Blue", "Red", "Red", "Blue", "Red", "Blue", "Yellow", "Blue", "Red", "Green", "Blue", "Yellow", "Yellow"]), 83)
Test.assert_equals(color_pattern_times(["Yellow", "Yellow", "Green", "Yellow", "Green", "Blue", "Yellow", "Red", "Red", "Yellow", "Blue", "Blue", "Blue", "Blue", "Green", "Red", "Red", "Yellow", "Green", "Red", "Red", "Yellow"]), 58)
Test.assert_equals(color_pattern_times(["Blue", "Red"]), 5)
Test.assert_equals(color_pattern_times(["Blue", "Red", "Red", "Blue", "Red", "Green", "Green"]), 18)
Test.assert_equals(color_pattern_times(["Red", "Green", "Green", "Yellow", "Yellow", "Yellow", "Red", "Green", "Yellow", "Yellow", "Green", "Blue", "Blue", "Blue", "Blue", "Yellow", "Blue", "Blue", "Blue", "Red", "Red", "Yellow", "Blue", "Red", "Blue", "Green", "Red", "Red"]), 72)
Test.assert_equals(color_pattern_times(["Yellow", "Green", "Green", "Green", "Yellow", "Yellow", "Yellow", "Green", "Yellow", "Yellow", "Blue", "Green", "Yellow", "Blue", "Red", "Red", "Green", "Yellow", "Blue", "Red", "Blue", "Yellow"]), 59)
Test.assert_equals(color_pattern_times(["Blue", "Green", "Blue", "Green", "Green", "Blue", "Red", "Green", "Red"]), 25)
Test.assert_equals(color_pattern_times(["Yellow"]), 2)
Test.assert_equals(color_pattern_times(["Green", "Yellow", "Red", "Green", "Yellow", "Blue", "Yellow", "Red", "Green", "Green", "Red", "Red", "Blue", "Red"]), 39)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Blue"]), 6)
Test.assert_equals(color_pattern_times(["Green", "Blue", "Blue", "Green", "Blue", "Green", "Blue", "Green", "Red", "Red", "Yellow", "Blue", "Blue", "Blue", "Blue", "Green", "Blue", "Green", "Blue", "Green", "Green", "Blue"]), 59)
Test.assert_equals(color_pattern_times(["Blue", "Blue", "Blue", "Blue"]), 8)
Test.assert_equals(color_pattern_times(["Red", "Blue", "Red", "Red", "Yellow", "Blue", "Yellow", "Blue", "Red", "Blue", "Green", "Yellow", "Green", "Yellow", "Red", "Red", "Red", "Green", "Red", "Yellow", "Blue", "Yellow", "Green", "Yellow", "Blue", "Green", "Blue", "Red", "Yellow", "Yellow"]), 85)
Test.assert_equals(color_pattern_times([]), 0)
"""
def color_pattern_times(number):
    color = len(number) * 2
    time = 0
    if len(number) > 0:
        for i,d in enumerate(number):
            if i != len(number)-1:
                if d != number[i+1]:
                    time +=1
    return color + time if len(number) > 0 else color

print(color_pattern_times(["Blue"]))
print(color_pattern_times(["Red", "Yellow", "Green", "Blue"]))
print(color_pattern_times(["Blue", "Blue", "Blue", "Red", "Red", "Red"]))

