import matplotlib.pyplot as plt
import networkx as nx

G = nx.Graph()
#ภาคเหนือ
G.add_edge('Chiang Rai',"Phayao",weight=92)
G.add_edge("Chiang Rai",'Lampang',weight=229)
G.add_edge('Chiang Rai',"Chiang Mai",weight=190)
G.add_edge('Phayao',"Nan",weight=148)
G.add_edge('Phayao',"Phrae",weight=143)
G.add_edge('Phayao',"Lampang",weight=142)
G.add_edge("Chiang Mai",'Mae Hong Son',weight=237)
G.add_edge('Chiang Mai',"Lampang",weight=114)
G.add_edge('Chiang Mai',"Lamphun",weight=39)
G.add_edge('Lampang',"Lamphun",weight=82)
G.add_edge('Lampang',"Tak",weight=188)
G.add_edge('Lampang',"Sukhothai",weight=195)
G.add_edge('Lampang',"Phrae",weight=96)
G.add_edge('Tak',"Mae Hong Son",weight=508)
G.add_edge('Tak',"Lamphun",weight=241)
G.add_edge('Tak',"Sukhothai",weight=85)
G.add_edge('Tak',"Kamphaeng Phe",weight=62)
G.add_edge('Phrae',"Nan",weight=119)
G.add_edge('Phrae',"Uttaradit",weight=72)
G.add_edge('Phrae',"Sukhothai",weight=163)
G.add_edge('Sukhothai',"Uttaradit",weight=91)
G.add_edge('Sukhothai',"Kamphaeng Phe",weight=71)
G.add_edge('Sukhothai',"Phitsanulok",weight=58)
G.add_edge('Phitsanulok',"Uttaradit",weight=108)
G.add_edge('Phitsanulok',"Nan",weight=293)
G.add_edge('Phitsanulok',"Kamphaeng Phe",weight=110)
G.add_edge('Phitsanulok',"Phichit",weight=57)
G.add_edge('Phitsanulok',"Phetchabun",weight=177)
G.add_edge('Phitsanulok',"Nakhon Sawan",weight=133)
G.add_edge('Nakhon Sawan',"Uthai Thani",weight=43)
G.add_edge('Nakhon Sawan',"Kamphaeng Phe",weight=132)
G.add_edge('Nakhon Sawan',"Phichit",weight=104)
G.add_edge('Nakhon Sawan',"Phetchabun",weight=174)
G.add_edge('Phichit',"Phetchabun",weight=133)
G.add_edge('Phichit',"Kamphaeng Phe",weight=100)

#ภาคกลาง
G.add_edge('Sara Buri',"Nakorn Nayok",weight=58)
G.add_edge("Sara Buri",'Prathum Thani',weight=85)
G.add_edge('Prathum Thani',"Non Buri",weight=27)
G.add_edge('Prathum Thani',"Bankok",weight=42)
G.add_edge('Prathum thani',"Nakorn Nayok",weight=117)
G.add_edge('Nakorn Nayok',"Prachin Buri",weight=20)
G.add_edge('Nakorn Nayok',"Chacherngsau",weight=75)
G.add_edge('Prachin Buri',"Bankok",weight=145)
G.add_edge('Prachin Buri',"Chacherngsau",weight=74)
G.add_edge('Prachin Buri',"Sakiaw",weight=104)
G.add_edge('Non Buri',"Bankok",weight=22)
G.add_edge('Bankok',"Chacherngsau",weight=85)
G.add_edge('Bankok',"Samut Prakarn",weight=26)
G.add_edge('Samut Prakarn',"Chon Buri",weight=70)
G.add_edge('Chon Buri',"Chacherngsau",weight=50)
G.add_edge('Chon Buri',"Rayong",weight=98)
G.add_edge('Rayong',"Chacherngsau",weight=135)
G.add_edge('Rayong',"Chantha Buri",weight=111)
G.add_edge('Chantha Buri',"Chacherngsau",weight=206)
G.add_edge('Chatha Buri',"Sakiaw",weight=161)
G.add_edge('Chatha Buri',"Trat",weight=69)
G.add_edge('Chacherngsau',"Sakiaw",weight=130)
G.add_edge('Nakorn Nayok',"Chachoengsao",weight=75)

#ภาตใต้
G.add_edge('Prachuap khiri khan','Chumporn',weight=189)
G.add_edge('Chumporn','Ranong',weight=126)
G.add_edge('Chumporn','Surat thani',weight=184)
G.add_edge('Ranong','Surat thani',weight=218)
G.add_edge('Ranong','Pangnga',weight=231)
G.add_edge('Pangnga','Surat thani',weight=159)
G.add_edge('Pangnga','Phuket',weight=87)
G.add_edge('Pangnga','Krabi',weight=74)
G.add_edge('Surat thani','Krabi',weight=156)
G.add_edge('Surat thani','Nakorn srithammarat',weight=140)
G.add_edge('Krabi','Nakorn srithammarat',weight=172)
G.add_edge('Krabi','Trang',weight=126)
G.add_edge('Nakorn srithammarat','Trang',weight=131)
G.add_edge('Nakorn srithammarat','Pattalung',weight=109)
G.add_edge('Trang','Pattalung',weight=58)
G.add_edge('Trang','Satool',weight=144)
G.add_edge('Pattalung','Songkhla',weight=122)
G.add_edge('Satool','Songkhla',weight=125)
G.add_edge('Songkhla','Pattani',weight=105)
G.add_edge('Songkhla','Yala',weight=131)
G.add_edge('Yala','Pattani',weight=60)
G.add_edge('Yala','Nara thiwad',weight=89)
G.add_edge('Pattani','Nara thiwad',weight=96)

#ภาคตะวันออกเฉียงเหนือ
G.add_edge('Loei','Nong Khai',weight=234)
G.add_edge('Loei','Nongbualamphu',weight=99)
G.add_edge('Loei','Khon Kaen',weight=207)
G.add_edge('Loei','Chaiyaphum',weight=227)
G.add_edge('Nong Khai','Udon Thani',weight=52)
G.add_edge('Nong Khai','Bueng Kan',weight=135)
G.add_edge('Nongbualamphu','Udon Thani',weight=51)
G.add_edge('Nongbualamphu','Khon Kaen',weight=118)
G.add_edge('Chaiyaphum','Khon Kaen',weight=140)
G.add_edge('Chaiyaphum','Nakhon Ratchasima',weight=121)
G.add_edge('Udon Thani','Bueng Kan',weight=207)
G.add_edge('Udon Thani','Sakon Nakhon',weight=166)
G.add_edge('Udon Thani','Kalasin',weight=147)
G.add_edge('Udon Thani','Khon Kaen',weight=121)
G.add_edge('Khon Kaen','Kalasin',weight=77)
G.add_edge('Khon Kaen','Maha Sarakham',weight=72)
G.add_edge('Khon Kaen','Nakhon Ratchasima',weight=192)
G.add_edge('Nakhon Ratchasima','Maha Sarakham',weight=214)
G.add_edge('Nakhon Ratchasima','Buri Ram',weight=127)
G.add_edge('Bueng Kan','Nakhon Phanom',weight=181)
G.add_edge('Bueng Kan','Sakon Nakhon',weight=195)
G.add_edge('Sakon Nakhon','Nakhon Phanom',weight=94)
G.add_edge('Sakon Nakhon','Mukdahan',weight=114)
G.add_edge('Sakon Nakhon','Kalasin',weight=129)
G.add_edge('Kalasin','Mukdahan',weight=164)
G.add_edge('Kalasin','Roi Et',weight=49)
G.add_edge('Kalasin','Maha Sarakham',weight=48)
G.add_edge('Maha Sarakham','Roi Et',weight=44)
G.add_edge('Maha Sarakham','Buri Ram',weight=149)
G.add_edge('Nakhon Phanom','Mukdahan',weight=110)
G.add_edge('Mukdahan','Roi Et',weight=149)
G.add_edge('Mukdahan','Yasothon',weight=115)
G.add_edge('Mukdahan','Amnat Charoen',weight=99)
G.add_edge('Roi Et','Yasothon',weight=68)
G.add_edge('Roi Et','Buri Ram',weight=149)
G.add_edge('Roi Et','Surin',weight=145)
G.add_edge('Roi Et','Si Sa Ket',weight=146)
G.add_edge('Buri Ram','Surin',weight=55)
G.add_edge('Si Sa Ket','Ubon Ratchathani',weight=65)
G.add_edge('Yasothon','Amnat Charoen',weight=57)
G.add_edge('Yasothon','Ubon Ratchathani',weight=103)
G.add_edge('Yasothon','Si Sa Ket',weight=103)
G.add_edge('Amnat Charoen','Ubon Ratchathani',weight=77)
G.add_edge('Surin','Si Sa Ket',weight=77)

#เชื่อมระหว่างจังหวัด
G.add_edge('Phitsanulok',"Khon Kaen",weight=321)
G.add_edge('Nakhon Ratchasima','Sara Buri',weight=148)
G.add_edge('Buri Ram','Sara Buri',weight=282)
G.add_edge('Nakhon Sawan',"Bangkok",weight=235)
G.add_edge('Kanchanaburi',"Bangkok",weight=135)
G.add_edge('Phetchaburi',"Bangkok",weight=134)
G.add_edge('Prachuap khiri khan','Phetchaburi',weight=159)
G.add_edge('Ranong','Phuket',weight=285)




try:
    again_loop = 'Y'
    while again_loop.lower() == 'Y' :
        print('===============')
        print('tell me the way to..?')
        print('1. No visit')
        print('2. 1 visit')
        print('3. 2 visit')
        print('4.Exit')
        print('===============')
        key_path = int(input('Enter your want find : '))
        if key_path == 1:
            prov_start = input('Province Start: ')
            prov_end = input('Province End: ')
            all_prov = list(nx.shortest_simple_paths(G,source=prov_start,target=prov_end,weight=None))
            for i,j in enumerate(all_prov):
                print(i,j)
    else:
        again = 'y'    
#        edge_labels = nx.get_edge_attributes(G,'weight')
#        pos = nx.spring_layout(G)
#        nx.draw(G,pos ,with_labels=True,font_color="black",font_size="5",node_size= 2000)
#        nx.draw_networkx_edge_labels(G,pos,edge_labels=edge_labels)
#        plt.show()
except:
    print('End')