import matplotlib.pyplot as plt
import networkx as nx

G = nx.Graph()

G.add_edge('Loei','Nong Khai',weight=234)
G.add_edge('Loei','Nongbualamphu',weight=99)
G.add_edge('Loei','Khon Kaen',weight=207)
G.add_edge('Loei','Chaiyaphum',weight=227)
G.add_edge('Nong Khai','Udon Thani',weight=52)
G.add_edge('Nong Khai','Bueng Kan',weight=135)
G.add_edge('Nongbualamphu','Udon Thani',weight=51)
G.add_edge('Nongbualamphu','Khon Kaen',weight=118)
G.add_edge('Chaiyaphum','Khon Kaen',weight=140)
G.add_edge('Chaiyaphum','Nakhon Ratchasima',weight=121)
G.add_edge('Udon Thani','Bueng Kan',weight=207)
G.add_edge('Udon Thani','Sakon Nakhon',weight=166)
G.add_edge('Udon Thani','Kalasin',weight=147)
G.add_edge('Udon Thani','Khon Kaen',weight=121)
G.add_edge('Khon Kaen','Kalasin',weight=77)
G.add_edge('Khon Kaen','Maha Sarakham',weight=72)
G.add_edge('Khon Kaen','Nakhon Ratchasima',weight=192)
G.add_edge('Nakhon Ratchasima','Maha Sarakham',weight=214)
G.add_edge('Nakhon Ratchasima','Buri Ram',weight=127)
G.add_edge('Bueng Kan','Nakhon Phanom',weight=181)
G.add_edge('Bueng Kan','Sakon Nakhon',weight=195)
G.add_edge('Sakon Nakhon','Nakhon Phanom',weight=94)
G.add_edge('Sakon Nakhon','Mukdahan',weight=114)
G.add_edge('Sakon Nakhon','Kalasin',weight=129)
G.add_edge('Kalasin','Mukdahan',weight=164)
G.add_edge('Kalasin','Roi Et',weight=49)
G.add_edge('Kalasin','Maha Sarakham',weight=48)
G.add_edge('Maha Sarakham','Roi Et',weight=44)
G.add_edge('Maha Sarakham','Buri Ram',weight=149)
G.add_edge('Nakhon Phanom','Mukdahan',weight=110)
G.add_edge('Mukdahan','Roi Et',weight=149)
G.add_edge('Mukdahan','Yasothon',weight=115)
G.add_edge('Mukdahan','Amnat Charoen',weight=99)
G.add_edge('Roi Et','Yasothon',weight=68)
G.add_edge('Roi Et','Buri Ram',weight=149)
G.add_edge('Roi Et','Surin',weight=145)
G.add_edge('Roi Et','Si Sa Ket',weight=146)
G.add_edge('Buri Ram','Surin',weight=55)
G.add_edge('Si Sa Ket','Ubon Ratchathani',weight=65)
G.add_edge('Yasothon','Amnat Charoen',weight=57)
G.add_edge('Yasothon','Ubon Ratchathani',weight=103)
G.add_edge('Yasothon','Si Sa Ket',weight=103)
G.add_edge('Amnat Charoen','Ubon Ratchathani',weight=77)
G.add_edge('Surin','Si Sa Ket',weight=77)

pos = nx.spring_layout(G)
nx.draw(G,pos ,with_labels=True,font_color="yellow",node_size= 2000)
plt.show()





